# Generated by Django 4.2.13 on 2024-06-12 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('period_type', models.CharField(choices=[('day', 'Daily'), ('month', 'Monthly'), ('year', 'Yearly')])),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
            ],
        ),
    ]
